hosts = 192.168.2.100
dn = cn=admin,dc=rouge,dc=iut
dnpass = admin
ldap_version = 3
base = ou=users,dc=rouge,dc=iut

passdb {
  pass_attrs = userPassword=password
  pass_filter = (&(objectClass=inetOrgPerson)(uid=%u))
}

userdb {
  user_attrs = =uid=5000,=gid=5000,=home=/var/mail/vmail/%u
  user_filter = (&(objectClass=inetOrgPerson)(uid=%u))
}