Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "client_admin1" do |admin1|
    admin1.vm.hostname = "client-admin1"
    admin1.vm.network "public_network", bridge: "enp3s0"
    admin1.vm.synced_folder "conf_client_admin1/", "/root/conf/"
    admin1.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
    admin1.vm.provision "shell", inline: <<-SHELL

     ip r add 192.168.0.0/16 via 192.168.4.190 dev eth1 || true
     ip r add 192.168.4.128 via 192.168.4.190 dev eth1 || true

      apt-get update
      apt-get install -y firefox-esr thunderbird xfce4 lightdm

    dhclient -r
    dhclient -v eth1

    cp /root/conf/resolv.conf /etc/resolv.conf

        id -u maxence &>/dev/null || adduser --gecos "" --disabled-password maxence
        echo "maxence:maxence" | chpasswd
        id -u sofiane &>/dev/null || adduser --gecos "" --disabled-password sofiane
        echo "sofiane:sofiane" | chpasswd
        id -u vincent &>/dev/null || adduser --gecos "" --disabled-password vincent

    SHELL
  end

  config.vm.define "client_admin2" do |admin2|
    admin2.vm.hostname = "client-admin2"
    admin2.vm.network "public_network", bridge: "enp3s0"
    admin2.vm.synced_folder "conf_client_admin2/", "/root/conf/"
    admin2.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
    admin2.vm.provision "shell", inline: <<-SHELL
    ip r add 192.168.0.0/16 via 192.168.4.190 dev eth1 || true
    ip r add 192.168.4.128 via 192.168.4.190 dev eth1 || true

      apt-get update
      apt-get install -y firefox-esr thunderbird xfce4 lightdm

    dhclient -r
    dhclient -v eth1
 
    cp /root/conf/resolv.conf /etc/resolv.conf
    
        id -u maxence &>/dev/null || adduser --gecos "" --disabled-password maxence
        echo "maxence:maxence" | chpasswd
        id -u sofiane &>/dev/null || adduser --gecos "" --disabled-password sofiane
        echo "sofiane:sofiane" | chpasswd
        id -u vincent &>/dev/null || adduser --gecos "" --disabled-password vincent
    SHELL
  end
end
