Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "ns" do |ns|
    ns.vm.hostname = "ns1"
    ns.vm.network "public_network", ip: "192.168.4.10", netmask: "255.255.255.192", bridge: "enp3s0"
    ns.vm.synced_folder "conf_ns1", "/root/conf/"
    ns.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y bind9
      cp /root/conf/db.* /var/cache/bind/
      cp /root/conf/named.conf.local /etc/bind/named.conf.local
      cp /root/conf/resolv.conf /etc/resolv.conf
      systemctl restart named
      ip r add 192.168.0.0/16 dev eth1 via 192.168.4.62 || true
    SHELL
  end

  config.vm.define "ns2" do |ns2|
    ns2.vm.hostname = "ns2"    
    ns2.vm.network "public_network", ip: "192.168.4.11", netmask: "255.255.255.192", bridge: "enp3s0"
    ns2.vm.synced_folder "conf_ns2/", "/root/conf/"
    ns2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y bind9
      cp /root/conf/named.conf.local /etc/bind/named.conf.local
      cp /root/conf/resolv.conf /etc/resolv.conf
      systemctl restart named
      ip r add 192.168.0.0/16 dev eth1 via 192.168.4.62 || true
    SHELL
  end

  config.vm.define "resolv" do |resolv|
    resolv.vm.hostname = "resolver"
    resolv.vm.network "public_network", ip: "192.168.4.20", netmask: "255.255.255.192", bridge: "enp3s0"
    resolv.vm.synced_folder "conf_resolver/", "/root/conf/"
    resolv.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y bind9
      cp /root/conf/named.conf.options /etc/bind/named.conf.options
      cp /root/conf/named.conf.local /etc/bind/named.conf.local
      cp /root/conf/resolv.conf /etc/resolv.conf
      systemctl restart named
      ip r add 192.168.0.0/16 dev eth1 via 192.168.4.62 || true
    SHELL
  end

  config.vm.define "server-web" do |web|
    web.vm.hostname = "server-web"
    web.vm.network "public_network", ip: "192.168.4.30", netmask: "255.255.255.192", bridge: "enp3s0"
    web.vm.synced_folder "conf_web/", "/root/conf/"
    web.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2
      cp -r /root/conf/* /var/www/html/
      cp /root/conf/resolv.conf /etc/resolv.conf
      ip r add 192.168.0.0/16 dev eth1 via 192.168.4.62 || true
      ip r add 192.168.4.128/26 via 192.168.4.62 || true
      ip r add 192.168.4.64/26 via 192.168.4.62 || true
    SHELL
  end

  config.vm.define "server-mail" do |mail|
    mail.vm.hostname = "server-mail"
    mail.vm.network "public_network", ip: "192.168.4.40", netmask: "255.255.255.192", bridge: "enp3s0"
    mail.vm.synced_folder "conf_mail/", "/root/conf/"
    mail.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y postfix dovecot-imapd dovecot-pop3d mailutils
      cp /root/conf/main.cf /etc/postfix/main.cf
      cp /root/conf/mailname /etc/mailname
      cp /root/conf/10-auth.conf /etc/dovecot/conf.d/10-auth.conf
      cp /root/conf/10-mail.conf /etc/dovecot/conf.d/10-mail.conf
      cp /root/conf/resolv.conf /etc/resolv.conf   
	id -u maxence &>/dev/null || adduser --gecos "" --disabled-password maxence
	echo "maxence:maxence" | chpasswd
	id -u sofiane &>/dev/null || adduser --gecos "" --disabled-password sofiane
	echo "sofiane:sofiane" | chpasswd
	id -u vincent &>/dev/null || adduser --gecos "" --disabled-password vincent
	echo "vincent:vincent" | chpasswd
      systemctl restart postfix dovecot
      ip r add 192.168.0.0/16 dev eth1 via 192.168.4.62 || true
    SHELL
  end

end
