# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    ip route replace 192.168.0.0/16 via 192.168.2.65
  SHELL

  config.vm.define "ws1" do |ws1|
    ws1.vm.hostname = "ws1-adm"
    ws1.vm.network "public_network",
      bridge: "enp4s0"
    ws1.vm.provider "virtualbox" do |vb|
      vb.gui = true
    end
    ws1.vm.provision "shell", inline: <<-SHELL
apt update
apt install -y firefox-esr thunderbird xauth

echo "session required pam_mkhomedir.so skel=/etc/skel umask=0022" >> /etc/pam.d/common-session

DEBIAN_FRONTEND=noninteractive apt install -y libnss-ldap libpam-ldap nslcd

cp /vagrant/ws/nsswitch.conf /etc/nsswitch.conf
cp /vagrant/ws/nslcd.conf /etc/nslcd.conf
chmod 640 /etc/nslcd.conf
chown root:nslcd /etc/nslcd.conf

systemctl stop nscd
systemctl disable nscd
systemctl mask nscd

systemctl enable nslcd
systemctl restart nslcd

apt install -y nfs-common

echo "192.168.2.101:/srv/nfs/homedirs /home nfs defaults,_netdev 0 0" >> /etc/fstab

dpkg-reconfigure -f noninteractive keyboard-configuration

DEBIAN_FRONTEND=noninteractive apt install -y mate-desktop-environment lightdm xorg

systemctl set-default graphical.target
systemctl enable lightdm

systemctl start lightdm

apt install -y console-data keyboard-configuration

loadkeys fr-latin9
localectl set-keymap fr-latin9

localectl set-x11-keymap fr pc105
setxkbmap fr || true

cat << 'EOF' > /etc/systemd/system/custom-route.service
[Unit]
Description=Add custom static route
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/sbin/ip route replace 192.168.0.0/16 via 192.168.2.65
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable custom-route.service
    SHELL
  end

  config.vm.define "ws2" do |ws2|
    ws2.vm.hostname = "ws2-adm"
    ws2.vm.network "public_network",
      bridge: "enp4s0"
    ws2.vm.provider "virtualbox" do |vb|
      vb.gui = true
    end
    ws2.vm.provision "shell", inline: <<-SHELL
apt update
apt install -y firefox-esr thunderbird xauth

echo "session required pam_mkhomedir.so skel=/etc/skel umask=0022" >> /etc/pam.d/common-session

DEBIAN_FRONTEND=noninteractive apt install -y libnss-ldap libpam-ldap nslcd

cp /vagrant/ws/nsswitch.conf /etc/nsswitch.conf
cp /vagrant/ws/nslcd.conf /etc/nslcd.conf
chmod 640 /etc/nslcd.conf
chown root:nslcd /etc/nslcd.conf

systemctl stop nscd
systemctl disable nscd
systemctl mask nscd

systemctl enable nslcd
systemctl restart nslcd

apt install -y nfs-common

echo "192.168.2.101:/srv/nfs/homedirs /home nfs defaults,_netdev 0 0" >> /etc/fstab

dpkg-reconfigure -f noninteractive keyboard-configuration

DEBIAN_FRONTEND=noninteractive apt install -y mate-desktop-environment lightdm xorg

systemctl set-default graphical.target
systemctl enable lightdm

systemctl start lightdm

apt install -y console-data keyboard-configuration

loadkeys fr-latin9
localectl set-keymap fr-latin9

localectl set-x11-keymap fr pc105
setxkbmap fr || true

cat << 'EOF' > /etc/systemd/system/custom-route.service
[Unit]
Description=Add custom static route
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/sbin/ip route replace 192.168.0.0/16 via 192.168.2.65
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable custom-route.service
    SHELL
  end
end
