Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "dhcp" do |dhcp|
    dhcp.vm.hostname = "dhcp"
    dhcp.vm.network "public_network", ip: "192.168.4.80", netmask: "255.255.255.192", bridge: "enp3s0"
    dhcp.vm.synced_folder "conf_dhcp/", "/root/conf/"
    dhcp.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y isc-dhcp-server
    cp /root/conf/dhcpd.conf /etc/dhcp/dhcpd.conf
    cp /root/conf/isc-dhcp-server /etc/default/isc-dhcp-server 
    systemctl restart isc-dhcp-server
    ip r add 192.168.0.0/16 via 192.168.4.126 dev eth1 || true
    ip r add 192.168.4.64 via 192.168.4.126 dev eth1 || true
SHELL
  end

   config.vm.define "ldap" do |ldap|
    ldap.vm.hostname = "ldap"
    ldap.vm.network "public_network", ip: "192.168.4.70", netmask: "255.255.255.192", bridge: "enp3s0"
    ldap.vm.synced_folder "conf_ldap/", "/root/conf/"
    ldap.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive

  apt-get update
  apt-get install -y slapd ldap-utils
  
  systemctl restart slapd
  ip r add 192.168.0.0/16 via 192.168.4.126 dev eth1 || true
  ip r add 192.168.4.64 via 192.168.4.126 dev eth1 || true
SHELL
  end

   config.vm.define "nfs" do |nfs|
    nfs.vm.hostname = "nfs"
    nfs.vm.network "public_network", ip: "192.168.4.90", netmask: "255.255.255.192", bridge: "enp3s0"
    nfs.vm.synced_folder "conf_nfs/", "/root/conf/"
    nfs.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nfs-kernel-server
      mkdir -p /home/users
      chown nobody:nogroup /home/users
      chmod 777 /home/users
      cp /root/conf/exports /etc/exports
      exportfs -a
      systemctl restart nfs-kernel-server
      ip r add 192.168.0.0/16 via 192.168.4.126 dev eth1 || true
      ip r add 192.168.4.64 via 192.168.4.126 dev eth1 || true
SHELL
  end

   config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "public_network", bridge: "enp3s0"
    client.vm.synced_folder "conf_client_info/", "/root/conf/"
    client.vm.provision "shell", inline: <<-SHELL
    ip r add 192.168.0.0/16 via 192.168.4.126 dev eth1 || true
    ip r add 192.168.4.64 via 192.168.4.126 dev eth1 || true
    apt-get update
    apt-get install -y firefox-esr thunderbird xfce4 lightdm
    cp /root/conf/resolv.conf /etc/resolv.conf
    dhclient -r 
    dhclient -v eth1

        id -u maxence &>/dev/null || adduser --gecos "" --disabled-password maxence
        echo "maxence:maxence" | chpasswd
        id -u sofiane &>/dev/null || adduser --gecos "" --disabled-password sofiane
        echo "sofiane:sofiane" | chpasswd
        id -u vincent &>/dev/null || adduser --gecos "" --disabled-password vincent
SHELL
client.vm.provider "virtualbox" do |v|
    v.memory = "4096"

	end
    end
end
