#!/bin/bash
INTERFACE="enp3s0"

sudo ip addr flush dev $INTERFACE
sudo ip link set dev $INTERFACE up
sudo ip addr add 192.168.4.61/26 dev $INTERFACE
sudo ip route add 192.168.0.0/16 via 192.168.4.62 dev $INTERFACE
